version: "3.8"
services:
  postgres:
    image: postgres:16rc1
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres