export const CONTENT_DATA_FIELD_NAME:string = 'content_data'
export const IS_PUBLISHED_FIELD_NAME:string = 'is_published'
export const OWNER_ID_FIELD_NAME:string = 'owner_id'
export const CREATED_AT_FIELD_NAME:string = 'created_at'
export const UPDATED_AT_FIELD_NAME:string = 'updated_at'