export type TMimeTypes =
  | 'image/jpg'
  | 'image/jpeg'
  | 'image/png'
  | 'application/pdf'
  | 'application/acad'
  | 'image/x-dwg'
  | 'image/vnd.dwg'
  | 'application/x-acad'
  | 'application/autocad_dwg'
  | 'application/dwg'
  | 'application/x-dwg'
  | 'application/x-autocad'
  | 'drawing/dwg'
  | 'drawing/x-dwf'; // Add all possible allowed types here